# Generated by Django 3.1.4 on 2020-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description. blah blah blah'),
            preserve_default=False,
        ),
    ]
